In [13]:
import pandas as pd

# Load the dataset into a DataFrame 
df = pd.read_csv("train.csv", encoding="latin-1")

df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   str
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   str
 6   Alley          91 non-null     str
 7   LotShape       1460 non-null   str
 8   LandContour    1460 non-null   str
 9   Utilities      1460 non-null   str
 10  LotConfig      1460 non-null   str
 11  LandSlope      1460 non-null   str
 12  Neighborhood   1460 non-null   str
 13  Condition1     1460 non-null   str
 14  Condition2     1460 non-null   str
 15  BldgType       1460 non-null   str
 16  HouseStyle     1460 non-null   str
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   str
 22  RoofMatl       1460 non-null   str
 23  Exterior1st    1460 non-null   str
 24  Exterior2nd    1460 non-null   str
 25  MasVnrType     588 non-null    str
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   str
 28  ExterCond      1460 non-null   str
 29  Foundation     1460 non-null   str
 30  BsmtQual       1423 non-null   str
 31  BsmtCond       1423 non-null   str
 32  BsmtExposure   1422 non-null   str
 33  BsmtFinType1   1423 non-null   str
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   str
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   str
 40  HeatingQC      1460 non-null   str
 41  CentralAir     1460 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   str
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   str
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    str
 58  GarageType     1379 non-null   str
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   str
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   str
 64  GarageCond     1379 non-null   str
 65  PavedDrive     1460 non-null   str
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      str
 73  Fence          281 non-null    str
 74  MiscFeature    54 non-null     str
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   str
 79  SaleCondition  1460 non-null   str
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), str(43)
memory usage: 924.0 KB

In [15]:
## This is way too much columns, I will only work with 10 of them

interesting_columns = df.columns[1:12] 
interesting_columns = interesting_columns.append(pd.Index([df.columns[-1]]))
df = df[interesting_columns]
df.drop(columns=["Alley"], inplace=True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MSSubClass   1460 non-null   int64
 1   MSZoning     1460 non-null   str
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1460 non-null   int64
 4   Street       1460 non-null   str
 5   LotShape     1460 non-null   str
 6   LandContour  1460 non-null   str
 7   Utilities    1460 non-null   str
 8   LotConfig    1460 non-null   str
 9   LandSlope    1460 non-null   str
 10  SalePrice    1460 non-null   int64
dtypes: float64(1), int64(3), str(7)
memory usage: 125.6 KB

In [19]:
df["LotFrontage"] = df["LotFrontage"].fillna(df["LotFrontage"].mean())

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MSSubClass   1460 non-null   int64
 1   MSZoning     1460 non-null   str
 2   LotFrontage  1460 non-null   float64
 3   LotArea      1460 non-null   int64
 4   Street       1460 non-null   str
 5   LotShape     1460 non-null   str
 6   LandContour  1460 non-null   str
 7   Utilities    1460 non-null   str
 8   LotConfig    1460 non-null   str
 9   LandSlope    1460 non-null   str
 10  SalePrice    1460 non-null   int64
dtypes: float64(1), int64(3), str(7)
memory usage: 125.6 KB

In [ ]:
## I will add a column, LotArea + LotFrontage

df["LotAreaPlusFrontage"] = df["LotArea"] + df["LotFrontage"]

# Another one, LotArea / LotFrontage

df["LotAreaDividedByFrontage"] = df["LotArea"] / df["LotFrontage"]

In [24]:
## Encode the categorical variables

categorical_columns = df.select_dtypes(include=['str']).columns

df_encoded = pd.get_dummies(df, columns=categorical_columns)

df_encoded.head()

,MSSubClass,LotFrontage,LotArea,SalePrice,MSZoning_C (all),MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,Street_Grvl,...,Utilities_AllPub,Utilities_NoSeWa,LotConfig_Corner,LotConfig_CulDSac,LotConfig_FR2,LotConfig_FR3,LotConfig_Inside,LandSlope_Gtl,LandSlope_Mod,LandSlope_Sev
0,0.073350,-0.229293,-0.207071,0.347154,False,False,False,True,False,False,...,True,False,False,False,False,False,True,True,False,False
1,-0.872264,0.451781,-0.091855,0.007286,False,False,False,True,False,False,...,True,False,False,False,True,False,False,True,False,False
2,0.073350,-0.093078,0.073455,0.535970,False,False,False,True,False,False,...,True,False,False,False,False,False,True,True,False,False
3,0.309753,-0.456318,-0.096864,-0.515105,False,False,False,True,False,False,...,True,False,True,False,False,False,False,True,False,False
4,0.073350,0.633401,0.375020,0.869545,False,False,False,True,False,False,...,True,False,False,False,True,False,False,True,False,False

In [ ]:
from sklearn.model_selection import train_test_split

X, y = df_encoded.drop(columns=["SalePrice"]), df_encoded["SalePrice"]

X_train_full, y_train_full, X_test, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train, y_train, X_val, y_val = train_test_split(X_train_full, y_train_full, test_size=0.2, random_state=42)

In [ ]:
## Scale the numeric columns

numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns

cols_mean_std = {}

for col in numerical_columns:
    cols_mean_std[col] = (X_train[col].mean(), X_train[col].std())
    X_train[col] = (X_train[col] - X_train[col].mean()) / X_train[col].std()
    
X_train.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,SalePrice
0,0.073350,RL,-0.229293,-0.207071,Pave,Reg,Lvl,AllPub,Inside,Gtl,0.347154
1,-0.872264,RL,0.451781,-0.091855,Pave,Reg,Lvl,AllPub,FR2,Gtl,0.007286
2,0.073350,RL,-0.093078,0.073455,Pave,IR1,Lvl,AllPub,Inside,Gtl,0.535970
3,0.309753,RL,-0.456318,-0.096864,Pave,IR1,Lvl,AllPub,Corner,Gtl,-0.515105
4,0.073350,RL,0.633401,0.375020,Pave,IR1,Lvl,AllPub,FR2,Gtl,0.869545

In [ ]:
# scale the validation and test sets using the mean and std of the training set

for col in numerical_columns:
    X_val[col] = (X_val[col] - cols_mean_std[col][0]) / cols_mean_std[col][1]
    X_test[col] = (X_test[col] - cols_mean_std[col][0]) / cols_mean_std[col][1]